### ISSUE TITLE
Determine why we need to lock VS Code to version `1.81.1` for integration tests to work in Travis

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/vscode-appland#811]
Currently, we need to lock the version of VS Code to `1.81.1` in the integration tests in order for them to work in Travis.

[Here is where it is specified](https://github.com/getappmap/vscode-appland/blob/develop/test/integrationTest.ts#L89).
[Here is a run of Travis that fails](https://app.travis-ci.com/github/getappmap/vscode-appland/builds/265813406).

**Comment by kgilpin** [comment]
Can we just drop Travis instead?

**Comment by kgilpin** [comment]
@dustinbyrne is this resolved now?

**Comment by ahtrotta** [comment]
I tried to resolve this a few weeks ago and it was still a problem. @kgilpin did you move this to `In Progress` because you're working on it?

**Comment by kgilpin** [comment]
I think the constraint has already been removed by @dustinbyrne

**Comment by ahtrotta** [comment]
Ah, yeah it was removed [here](https://github.com/getappmap/vscode-appland/commit/5456750817f7f4d2608404d8ea018e2a56fa74b2)
